### ISSUE TITLE
no colour control only white/warm white?

### ISSUE THREAD

**Issue by fredtj** [JamesSwift/localbytes-bulb-9w-rgbct#1]
Hi and thanks for the config! Am using the plug config without issue.

The bulb however, doesn't seem to offer control of RGB, only white and warm white (along with some RGB max power values)? not sure if user error, but here is a screenshot [https://postimg.cc/BLTtD8Vd](https://postimg.cc/BLTtD8Vd)

Any ideas how I can debug this?

**Comment by JamesSwift** [comment]
Hi. At the moment, the built-in esphome webserver doesn't provide colour controls for the light component. We should probably raise a feature request for that with them. However you can control the colour through home assistant in the usual way:

![Screenshot_20230226-141410](https://user-images.githubusercontent.com/2080205/221415952-f9381dd6-33f6-4728-92a8-f162b5743b02.png)

**Comment by fredtj** [comment]
And so it is! Thank you!
