### ISSUE TITLE
I've bricked my bulb - help!

### ISSUE THREAD

**Issue by peterthevicar** [JamesSwift/localbytes-bulb-9w-rgbct#2]
My localbytes bulb arrived today and I thought I'd flash it straight over to ESPHome.
 
I opened the tasmota webserver, and tried to upload minimal.bin. I got the "too big" error, also with the full .bin.

So next I gave it my wifi network credentials, then it let me upload minimal.bin (v1.0) successfully

That rebooted and came up with the ESPHome webserver but when I tried to update the firmware with the full .bin it just went dead on me. I hadn't re-entered my network credentials.

It's still connecting to my network, so it's remembered the credentials from setting up tasmota, but all ports are closed according to nmap.

I've tried switching off and on again 7 times as per tasmota reset but no joy.

Is that the end of my bulb, or is there a way to bring it back to life?

TIA Peter

**Comment by JamesSwift** [comment]
Oh dear, that's not good. I'm confused as to how it is still connecting to your network though, if you never entered the credentials into the esphome minimal firmware. If you saw the esphome interface at all, then the tasmota firmware and it's settings should be completely gone. Are you sure it's not putting out its recovery WiFi hotspot?

**Comment by peterthevicar** [comment]
Blimey that was quick! I'm similarly confused over the continuing connection. Definitely no sign of any WiFi hotspot. I've been checking a lot! Is there any strange pattern of switching on and off which might help?

**Comment by JamesSwift** [comment]
Not that I'm aware of I'm afraid. I wonder if you turn off your WiFi router and restart the bulb if it will turn on its recovery hotspot again?

 If you're handy with a soldering iron and have serial to USB board you may be able to solder some leads onto the serial pins and get the log output that way, or reflash it. But its likely a difficult and destructive repair.

**Comment by peterthevicar** [comment]
Just checked again and it's actually NOT connected to the network, must have been a cache somewhere reporting that. So at least that mystery is solved. I did try taking it out of WiFi range and restarting but no hotspot came up. I'll try localbytes in case they can help. Thank you so much for your time.
Best wishes, Peter

**Comment by JamesSwift** [comment]
Hope you find a solution.

**Comment by peterthevicar** [comment]
Thanks, I'll let you know!

**Comment by dcelasun** [comment]
@peterthevicar did you find a solution to this? I'm afraid mine is bricked as well :/

**Comment by peterthevicar** [comment]
No sorry, it just went in the bin.

**Comment by dcelasun** [comment]
Thanks. Mine is destined for the same, it seems :/
